import canonicalize from "canonicalize";
import { Buffer } from "buffer";
import { createSign, createVerify } from "node:crypto";

/**
 * Dakota endorsed-request signing.
 *
 * Pipeline (per docs.dakota.xyz/documentation/wallet-signing):
 *   intent JSON → RFC 8785 (JCS) canonicalization → SHA-256 → ECDSA P-256 → ASN.1 DER → base64
 *
 * Dakota's server re-canonicalizes the submitted intent and verifies the
 * signature against registered signer public keys, so wire formatting doesn't
 * matter — but the signed bytes must match the canonical form exactly.
 * Amounts must be decimal strings, and optional fields must be omitted
 * entirely (never null): canonicalization keeps null but drops undefined.
 */

export interface TransferOperation {
  kind: "transfer";
  from: string;
  to: string;
  /** Decimal string, e.g. "10.5" — never a number. */
  amount: string;
  asset_id: string;
}

export interface EvmContractCallOperation {
  kind: "evm_contract_call";
  from: string;
  to: string;
  asset_id: string;
  method?: string;
  args?: string[];
  data?: string;
}

export type TransactionOperation = TransferOperation | EvmContractCallOperation;

/** The one intent type without a `type` discriminator (send transaction). */
export interface SendTransactionIntent {
  wallet_id: string;
  caip2: string;
  operation: TransactionOperation;
  idempotency_key: string;
  context_digest?: string;
}

/** Body shape for all endorsed endpoints — signatures + intent, no wrapper. */
export interface EndorsedRequest<I extends object = Record<string, unknown>> {
  signatures: string[];
  intent: I;
}

function pruneUndefined(value: unknown, path: string): unknown {
  if (value === null) {
    throw new Error(
      `Intent field "${path}" is null — Dakota requires optional fields to be omitted, not null`
    );
  }
  if (Array.isArray(value)) {
    return value.map((item, i) => pruneUndefined(item, `${path}[${i}]`));
  }
  if (typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
      if (val === undefined) continue;
      out[key] = pruneUndefined(val, path ? `${path}.${key}` : key);
    }
    return out;
  }
  return value;
}

/**
 * RFC 8785 canonical JSON of an intent, with undefined fields stripped.
 * Throws on null fields so a bad intent fails here instead of as an opaque
 * `invalid_signature` from Dakota.
 */
export function canonicalizeIntent(intent: object): string {
  const pruned = pruneUndefined(intent, "");
  const canonical = canonicalize(pruned);
  if (canonical === undefined) {
    throw new Error("Intent could not be canonicalized");
  }
  return canonical;
}

/** Sign an intent with an ECDSA P-256 private key (PEM). Returns base64 DER. */
export function signIntent(intent: object, privateKeyPem: string): string {
  const canonical = canonicalizeIntent(intent);
  const signer = createSign("SHA256");
  signer.update(canonical, "utf8");
  return signer.sign({ key: privateKeyPem, dsaEncoding: "der" }).toString("base64");
}

/** Mirror of Dakota's server-side check — used by tests and the bootstrap script. */
export function verifyIntentSignature(
  intent: object,
  signatureB64: string,
  publicKeyPem: string
): boolean {
  const canonical = canonicalizeIntent(intent);
  const verifier = createVerify("SHA256");
  verifier.update(canonical, "utf8");
  return verifier.verify(
    { key: publicKeyPem, dsaEncoding: "der" },
    Buffer.from(signatureB64, "base64")
  );
}

/**
 * Platform signer private key from DAKOTA_SIGNER_PRIVATE_KEY, which holds the
 * PKCS#8 PEM base64-encoded so it fits a single env line.
 * Generated by scripts/dakota-bootstrap.ts (see DAKOTA-PLAN.md §4).
 */
export function getPlatformSignerKey(): string {
  const encoded = process.env.DAKOTA_SIGNER_PRIVATE_KEY;
  if (!encoded) {
    throw new Error(
      "DAKOTA_SIGNER_PRIVATE_KEY is not configured — run scripts/dakota-bootstrap.ts to generate the platform signer keypair"
    );
  }
  const pem = Buffer.from(encoded, "base64").toString("utf8");
  if (!pem.includes("PRIVATE KEY")) {
    throw new Error(
      "DAKOTA_SIGNER_PRIVATE_KEY must be a base64-encoded PKCS#8 PEM private key"
    );
  }
  return pem;
}
